#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# dependencies = []
# ///
"""docs.py — the project's team docs in one layout people can read on GitHub (v26).

    D=<CORE_DIR>/scripts/core/docs.py
    uv run $D where architecture                  # → docs/architecture/architecture.md (or .aizen/knowledge/… )
    uv run $D where module-api --name seat-hold   # → docs/api/seat-hold.md
    uv run $D index                               # rebuild the generated part of docs/README.md
    uv run $D check                               # layout, titles, summaries, links; exit 1 on problems
    uv run $D migrate [--apply]                   # plan (or do) the move to the layout; --apply also sets "docs": "docs"
    uv run $D --selfcheck

Where design docs live is a project setting, `.aizen/config/guard.json` → "docs":
  "docs"       team docs in docs/ (committed, readable on GitHub) — the default for projects set up from v26.1
  "knowledge"  the agents' local .aizen/knowledge/ (not committed) — what older projects have until they migrate
decisions.md and lessons.md always stay in .aizen/knowledge/ (the agents' memory); a decision the team must know
becomes an ADR in docs/architecture/adr/. Layout and writing rules: references/core/docs.md.
Python ≥ 3.9, standard library only.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

SECTIONS = {  # folder → (title in the index, what goes there)
    "product": ("Sản phẩm", "ý tưởng, yêu cầu (SRS), user story, phạm vi, thuật ngữ, kế hoạch kiểm thử"),
    "architecture": ("Kiến trúc", "tổng quan, thành phần, luồng, bảo mật, thiết kế module, ADR"),
    "api": ("API", "hợp đồng API theo module/service: .md + OpenAPI .yaml"),
    "data": ("Dữ liệu", "ERD, bảng, DDL, migration, dữ liệu theo module"),
    "ui": ("Giao diện", "kiến trúc frontend, màn hình, design tokens, ảnh xuất từ Figma"),
    "ops": ("Vận hành", "môi trường, biến môi trường, hạ tầng, deploy, runbook"),
    "guides": ("Hướng dẫn", "onboarding, cách chạy, đóng góp, how-to cho dev"),
    "services": ("Service", "microservice: mỗi service một thư mục, cùng bố cục"),
}
ASSET_EXT = {".yaml", ".yml", ".json", ".sql", ".png", ".jpg", ".jpeg", ".svg", ".gif", ".webp", ".mmd", ".puml",
             ".html", ".drawio", ".pdf", ".csv"}
KEEP = "<!-- docs-index: everything below is generated by docs.py index — edit above this line -->"

# logical name → (path under .aizen/knowledge/, path under docs/); {n} = --name (module, app or service)
MAP = {
    "overview": ("system/overview.md", "product/overview.md"),
    "idea": ("system/idea.md", "product/idea.md"),
    "requirements": ("system/requirements.md", "product/requirements.md"),
    "test-plan": ("system/test-plan.md", "product/test-plan.md"),
    "system-map": ("system/system-map.md", "architecture/system-map.md"),
    "architecture": ("system/architecture.md", "architecture/architecture.md"),
    "flows": ("system/flows.md", "architecture/flows.md"),
    "security": ("system/security.md", "architecture/security.md"),
    "data": ("system/data.md", "data/data.md"),
    "infrastructure": ("system/infrastructure.md", "ops/infrastructure.md"),
    "module-design": ("modules/{n}/{n}-design.md", "architecture/modules/{n}.md"),
    "module-database": ("modules/{n}/{n}-database.md", "data/{n}.md"),
    "module-api": ("modules/{n}/{n}-api.md", "api/{n}.md"),
    "module-api-yaml": ("modules/{n}/{n}-api.yaml", "api/{n}.yaml"),
    "app-frontend": ("apps/{n}/{n}-frontend.md", "ui/{n}-frontend.md"),
    "app-ui": ("apps/{n}/{n}-ui.md", "ui/{n}-ui.md"),
    "service-overview": ("services/{n}/{n}-overview.md", "services/{n}/overview.md"),
    "service-api": ("services/{n}/{n}-api.md", "services/{n}/api.md"),
    "service-database": ("services/{n}/{n}-database.md", "services/{n}/database.md"),
    "service-infrastructure": ("services/{n}/{n}-infrastructure.md", "services/{n}/infrastructure.md"),
    "adr": (None, "architecture/adr/{n}.md"),
    "decisions": ("decisions.md", None),
    "lessons": ("lessons.md", None),
}
# a project's own name for a doc that has a logical name — `where` returns it when the standard name is absent
ALIASES = {
    "requirements": ("srs.md", "prd.md", "requirements-spec.md"),
    "architecture": ("hld.md", "architecture-overview.md", "system-design.md"),
    "data": ("data-model.md", "erd.md", "database.md"),
    "security": ("threat-model.md", "security-model.md"),
    "infrastructure": ("infra.md", "infrastructure-topology.md"),
}
GUESS = [  # (pattern on the file name, folder) — first match wins; for `migrate`
    (r"\badr\b|^\d{3,4}-", "architecture/adr"),
    (r"openapi|swagger|\bapi\b|endpoint|contract", "api"),
    (r"\.sql$|\bddl\b|\berd\b|schema|database|\bdb\b|migration|\bdata\b", "data"),
    (r"infra|deploy|\benv\b|environment|runbook|procedure|\bops\b|docker|k8s|kubernetes|helm|ci-?cd|pipeline", "ops"),
    (r"\bui\b|\bux\b|screen|wireframe|figma|frontend|design-tokens", "ui"),
    (r"architect|\bhld\b|\blld\b|\bc4\b|flow|sequence|security|threat|component|module|system-map", "architecture"),
    (r"capacity|\bload\b|performance|\bnfr\b|sizing|scal", "architecture"),
    (r"guide|onboard|setup|how-?to|contributing|getting-started", "guides"),
    (r"srs|requirement|\bprd\b|user-stor|use-case|glossary|scope|overview|idea|vision|test-plan|acceptance", "product"),
]


# ── settings and paths ───────────────────────────────────────────────────────────────────────────────────

def find_ws(start: Path) -> Path | None:
    p = start.resolve()
    if ".aizen" in p.parts:
        p = Path(*p.parts[:p.parts.index(".aizen")])
    for d in (p, *p.parents):
        if (d / ".aizen").is_dir() or (d / ".git").exists():
            return d
    return None


def config(ws: Path) -> dict:
    try:
        return json.loads((ws / ".aizen" / "config" / "guard.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def mode(ws: Path) -> str:
    return "docs" if config(ws).get("docs") == "docs" else "knowledge"


def where(ws: Path, key: str, name: str | None = None) -> str:
    """Workspace-relative path of a logical doc under this project's setting."""
    if key not in MAP:
        raise ValueError(f"unknown doc {key!r} — one of: {', '.join(MAP)}")
    kn, dc = MAP[key]
    if "{n}" in (dc or kn or "") and not name:
        raise ValueError(f"{key} needs --name (the module, app or service)")
    if mode(ws) == "docs" and dc:
        path = "docs/" + dc.format(n=name)
        if not (ws / path).exists():
            folder = (ws / path).parent
            alt = next((folder / a for a in ALIASES.get(key, ()) if (folder / a).is_file()), None)
            if alt:
                return alt.relative_to(ws).as_posix()
        return path
    if kn is None:
        return "docs/" + dc.format(n=name)
    return ".aizen/knowledge/" + kn.format(n=name)


def is_doc_path(ws: Path, rel: str) -> bool:
    """A write the `knowledge` check counts: the agents' knowledge, or team docs when the project publishes them."""
    return rel.startswith(".aizen/knowledge/") or (mode(ws) == "docs" and rel.startswith("docs/"))


def modules(ws: Path) -> dict[str, list[str]]:
    """{module: [doc paths]} — design, API and data docs grouped by module name."""
    out: dict[str, list[str]] = {}
    if mode(ws) == "docs":
        system = {where(ws, k) for k, (_, dc) in MAP.items() if dc and "{n}" not in dc}
        for key in ("module-design", "module-database", "module-api"):
            folder = ws / "docs" / MAP[key][1].split("{n}")[0]
            for f in sorted(folder.glob("*.md")) if folder.is_dir() else []:
                rel = f.relative_to(ws).as_posix()
                if rel not in system and f.name != "README.md":
                    out.setdefault(f.stem, []).append(rel)
    else:
        base = ws / ".aizen" / "knowledge" / "modules"
        for d in sorted(p for p in base.glob("*") if p.is_dir()) if base.is_dir() else []:
            out[d.name] = [f.relative_to(ws).as_posix() for f in sorted(d.glob("*.md"))]
    return dict(sorted(out.items()))


def system_extras(ws: Path, known: set[str]) -> list[str]:
    """Architecture-level docs that have no logical name (shown under Kiến trúc in PROJECT.md)."""
    folder = ws / ("docs/architecture" if mode(ws) == "docs" else ".aizen/knowledge/system")
    skip = {"overview.md", "system-map.md", "idea.md"}
    return [f.relative_to(ws).as_posix() for f in sorted(folder.glob("*.md")) if folder.is_dir()
            and f.relative_to(ws).as_posix() not in known and f.name not in skip]


# ── reading a doc ────────────────────────────────────────────────────────────────────────────────────────

def title_and_summary(p: Path) -> tuple[str, str]:
    text = p.read_text(encoding="utf-8", errors="replace")
    title, summary, fence = "", "", False
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("```"):
            fence = not fence
            continue
        if fence or not s or s.startswith("<!--"):
            continue
        if not title:
            if s.startswith("# "):
                title = s[2:].strip()
                continue
            break
        if s.startswith(">"):
            continue  # status / metadata line ("> DRAFT v3 · …") — not the summary
        if s.startswith(("#", "|", "-", "*", "!", "<")) or re.match(r"^\d+\.", s):
            break
        summary = s
        break
    return title, summary


def doc_files(ws: Path) -> list[Path]:
    root = ws / "docs"
    return sorted(p for p in root.rglob("*") if p.is_file() and ".git" not in p.parts) if root.is_dir() else []


# ── index ────────────────────────────────────────────────────────────────────────────────────────────────

def build_index(ws: Path) -> str:
    rows: dict[str, list[str]] = {}
    for p in doc_files(ws):
        rel = p.relative_to(ws / "docs")
        if rel.as_posix() == "README.md" or len(rel.parts) < 2:
            continue
        if p.suffix != ".md":
            if p.suffix.lower() in {".yaml", ".yml", ".json", ".sql", ".csv", ".pdf", ".drawio"} and "diagrams" not in rel.parts:
                rows.setdefault(rel.parts[0], []).append(f"| [`{rel.name}`]({rel.as_posix()}) | tệp kèm ({p.suffix[1:]}) |")
            continue
        title, summary = title_and_summary(p)
        rows.setdefault(rel.parts[0], []).append(
            f"| [{title or p.stem}]({rel.as_posix()}) | {summary[:140] or '—'} |")
    out = [KEEP, "", "## Mục lục", ""]
    for folder, (name, what) in SECTIONS.items():
        if folder not in rows:
            continue
        out += [f"### {name} — `{folder}/`", "", f"_{what}_", "", "| Tài liệu | Nội dung |", "|---|---|",
                *rows.pop(folder), ""]
    for folder in sorted(rows):
        out += [f"### `{folder}/` (ngoài bố cục chuẩn)", "", "| Tài liệu | Nội dung |", "|---|---|", *rows[folder], ""]
    return "\n".join(out).rstrip() + "\n"


def write_index(ws: Path) -> Path:
    p = ws / "docs" / "README.md"
    head = f"# Tài liệu — {ws.resolve().name}\n\nBắt đầu từ đây: mỗi thư mục một chủ đề, mỗi tài liệu một dòng tóm tắt.\n"
    if p.is_file():
        head = p.read_text(encoding="utf-8").split(KEEP, 1)[0].rstrip() + "\n"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(head + "\n" + build_index(ws), encoding="utf-8", newline="\n")
    return p


# ── check ────────────────────────────────────────────────────────────────────────────────────────────────

KEBAB = re.compile(r"^[a-z0-9]+(?:[.-][a-z0-9]+)*$")
LINK = re.compile(r"\]\(([^)\s]+?)(?:\s+\"[^\"]*\")?\)")


def run_ids(ws: Path) -> list[str]:
    """Ids of this project's Aizen runs (live and archived) that look like task codes — they must not leak into docs."""
    ids = set()
    for d in ("runs", "archive"):
        base = ws / ".aizen" / d
        ids |= {p.name for p in base.iterdir() if p.is_dir() and re.search(r"\d", p.name)} if base.is_dir() else set()
    return sorted(ids)


def check(ws: Path) -> list[str]:
    problems = []
    ids = run_ids(ws)
    root = ws / "docs"
    if not root.is_dir():
        return ["docs/ does not exist — `docs.py index` creates docs/README.md"]
    readme = root / "README.md"
    if not readme.is_file():
        problems.append("docs/README.md missing — run `docs.py index`")
    elif KEEP not in readme.read_text(encoding="utf-8") or \
            readme.read_text(encoding="utf-8").split(KEEP, 1)[1].strip() != build_index(ws).split(KEEP, 1)[1].strip():
        problems.append("docs/README.md index is stale — run `docs.py index`")
    for p in doc_files(ws):
        rel = p.relative_to(root)
        r = f"docs/{rel.as_posix()}"
        if len(rel.parts) == 1 and rel.name != "README.md":
            problems.append(f"{r}: at the docs/ root — move it into a section ({', '.join(SECTIONS)}); `docs.py migrate`")
        elif len(rel.parts) > 1 and rel.parts[0] not in SECTIONS:
            problems.append(f"{r}: folder `{rel.parts[0]}/` is not a section ({', '.join(SECTIONS)})")
        if rel.name != "README.md" and (not KEBAB.match(p.stem.lower()) or p.stem != p.stem.lower()):
            problems.append(f"{r}: name is not lower-kebab-case")
        if p.suffix != ".md":
            if p.suffix.lower() not in ASSET_EXT:
                problems.append(f"{r}: unexpected file type in docs/")
            continue
        if rel.name == "README.md" and len(rel.parts) == 1:
            continue
        title, summary = title_and_summary(p)
        if not title:
            problems.append(f"{r}: no `# Title` on the first line")
        elif not summary:
            problems.append(f"{r}: no one-line summary under the title (what it is, for whom)")
        text = p.read_text(encoding="utf-8", errors="replace")
        if ".aizen/" in text and not any(".aizen/" in x for x in LINK.findall(text)):
            problems.append(f"{r}: mentions .aizen/ — that folder is not in the repository; copy the conclusion instead")
        leaked = [i for i in ids if re.search(rf"(?<![\w-]){re.escape(i)}(?![\w-])", text)]
        if leaked:
            problems.append(f"{r}: mentions run id {', '.join(leaked[:3])} — docs describe the product, not the agent runs")
        for link in LINK.findall(text):
            if re.match(r"^(https?:|mailto:|#)", link):
                continue
            target = link.split("#", 1)[0]
            if ".aizen/" in target:
                problems.append(f"{r}: links into .aizen/ ({target}) — that folder is not in the repository")
            elif target and not (p.parent / target).resolve().exists():
                problems.append(f"{r}: broken link {target}")
    return problems


# ── migrate ──────────────────────────────────────────────────────────────────────────────────────────────

def kebab(name: str) -> str:
    stem, dot, ext = name.rpartition(".")
    stem = stem if dot else name
    s = re.sub(r"[^a-z0-9]+", "-", re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", stem)).lower()).strip("-") or "doc"
    return f"{s}.{ext.lower()}" if dot else s


DESIGN_SIGNS = re.compile(r"```mermaid|sequenceDiagram|stateDiagram|state machine|\bendpoint|\bAPI\b|\bschema\b|"
                          r"luồng|trạng thái|bảng\b|interface|\bInterface:|\bData:", re.I)
PRODUCT_SIGNS = re.compile(r"\b(FR|NFR|BR|US)-\d+|user stor|use case|yêu cầu|actor|persona", re.I)


def guess(name: str, text: str = "") -> tuple[str, bool]:
    """Folder for a loose doc: by its name first, then by what it contains (a feature-area design → modules)."""
    low = kebab(name)
    for rx, folder in GUESS:
        if re.search(rx, low):
            return folder, True
    if name.endswith(".md") and text:
        design, product = len(DESIGN_SIGNS.findall(text)), len(PRODUCT_SIGNS.findall(text))
        if design >= 3 and design >= product:
            return "architecture/modules", False
        if product >= 3:
            return "product", False
    return "product", False


def plan_migration(ws: Path) -> list[tuple[str, str, str]]:
    """[(from, to, note)] — knowledge files into docs/, then docs/ files outside the layout into a section."""
    moves = []
    kroot = ws / ".aizen" / "knowledge"
    reverse = {}
    for key, (kn, dc) in MAP.items():
        if kn and dc:
            reverse[kn] = dc
    for f in sorted(kroot.rglob("*")) if kroot.is_dir() else []:
        if not f.is_file():
            continue
        k = f.relative_to(kroot).as_posix()
        for kn, dc in reverse.items():
            rx = "^" + re.escape(kn).replace(re.escape("{n}"), "(?P<n>[^/]+)", 1).replace(re.escape("{n}"), "(?P=n)") + "$"
            m = re.match(rx, k)
            if m:
                moves.append((f".aizen/knowledge/{k}", "docs/" + dc.format(n=m.groupdict().get("n")), "knowledge → docs"))
                break
    root = ws / "docs"
    for p in doc_files(ws):
        rel = p.relative_to(root)
        if rel.as_posix() == "README.md":
            continue
        inside = len(rel.parts) > 1 and rel.parts[0] in SECTIONS
        name = kebab(rel.name)
        if inside and name == rel.name:
            continue
        folder, sure = (Path(*rel.parts[:-1]).as_posix(), True) if inside else \
            guess(rel.name, p.read_text(encoding="utf-8", errors="replace") if p.suffix == ".md" else "")
        moves.append((f"docs/{rel.as_posix()}", f"docs/{folder}/{name}", "" if sure else "đoán — kiểm lại"))
    return moves


def tracked(ws: Path, rel: str) -> bool:
    r = subprocess.run(["git", "ls-files", "--error-unmatch", rel], cwd=ws, capture_output=True)
    return r.returncode == 0


def apply_migration(ws: Path, moves: list[tuple[str, str, str]]) -> list[str]:
    done = []
    for src, dst, _ in moves:
        s, d = ws / src, ws / dst
        if d.exists():
            done.append(f"skip {src}: {dst} exists")
            continue
        d.parent.mkdir(parents=True, exist_ok=True)
        if tracked(ws, src):
            subprocess.run(["git", "mv", src, dst], cwd=ws, check=True)
        else:
            shutil.move(str(s), str(d))
        done.append(f"{src} → {dst}")
    cp = ws / ".aizen" / "config" / "guard.json"
    if cp.parent.is_dir():
        cfg = config(ws)
        cfg["docs"] = "docs"
        cp.write_text(json.dumps(cfg, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        done.append('.aizen/config/guard.json: "docs": "docs"')
    return done


# ── CLI ──────────────────────────────────────────────────────────────────────────────────────────────────

def main(argv=None) -> int:
    for s in (sys.stdout, sys.stderr):
        try:
            s.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--selfcheck", action="store_true")
    sub = ap.add_subparsers(dest="cmd")
    w = sub.add_parser("where", help="path of a logical doc")
    w.add_argument("key", choices=list(MAP))
    w.add_argument("--name", help="module, app or service")
    sub.add_parser("index", help="rebuild the generated part of docs/README.md")
    sub.add_parser("check", help="layout, titles, summaries, links")
    m = sub.add_parser("migrate", help="plan (or do with --apply) the move into the layout")
    m.add_argument("--apply", action="store_true")
    for q in sub.choices.values():
        q.add_argument("--workspace", default=".")
    a = ap.parse_args(argv)
    if a.selfcheck:
        return _selfcheck()
    if not a.cmd:
        ap.print_help()
        return 2
    ws = find_ws(Path(a.workspace))
    if ws is None:
        print("not inside a project (no .aizen/ or .git above)", file=sys.stderr)
        return 2
    if a.cmd == "where":
        try:
            print(where(ws, a.key, a.name))
        except ValueError as e:
            print(e, file=sys.stderr)
            return 2
    elif a.cmd == "index":
        print(f"✓ {write_index(ws).relative_to(ws).as_posix()}")
    elif a.cmd == "check":
        problems = check(ws)
        print("\n".join(f"✗ {p}" for p in problems) if problems else "✓ docs/ follows the layout")
        return 1 if problems else 0
    else:
        moves = plan_migration(ws)
        if not moves:
            print("✓ nothing to move")
        elif a.apply:
            print("\n".join(apply_migration(ws, moves)))
            print(f"✓ {write_index(ws).relative_to(ws).as_posix()} — review with `git status`, then commit")
        else:
            print("Dự kiến chuyển (chạy lại với --apply để làm):")
            print("\n".join(f"  {s}  →  {d}{'   (' + n + ')' if n and n != 'knowledge → docs' else ''}" for s, d, n in moves))
    return 0


def _selfcheck() -> int:
    import tempfile
    with tempfile.TemporaryDirectory() as t:
        ws = Path(t)
        subprocess.run(["git", "init", "-q"], cwd=ws, check=True)
        (ws / ".aizen" / "config").mkdir(parents=True)
        cfg = ws / ".aizen" / "config" / "guard.json"
        cfg.write_text("{}", encoding="utf-8")
        assert where(ws, "architecture") == ".aizen/knowledge/system/architecture.md"
        assert where(ws, "module-api", "seat-hold") == ".aizen/knowledge/modules/seat-hold/seat-hold-api.md"
        assert where(ws, "decisions") == ".aizen/knowledge/decisions.md"
        assert where(ws, "adr", "0001-use-postgres") == "docs/architecture/adr/0001-use-postgres.md"
        try:
            where(ws, "module-api")
            raise AssertionError("module-api without a name must fail")
        except ValueError:
            pass
        # knowledge + loose docs → migrate plan
        k = ws / ".aizen" / "knowledge"
        (k / "system").mkdir(parents=True)
        (k / "modules" / "seat-hold").mkdir(parents=True)
        (k / "system" / "architecture.md").write_text("# Kiến trúc\n\nTổng quan hệ thống.\n", encoding="utf-8")
        (k / "modules" / "seat-hold" / "seat-hold-api.md").write_text("# API giữ ghế\n\nHợp đồng API.\n", encoding="utf-8")
        (k / "decisions.md").write_text("# D\n", encoding="utf-8")
        (ws / "docs").mkdir()
        (ws / "docs" / "SRS.md").write_text("# SRS\n\nYêu cầu phần mềm vé tàu Tết.\n", encoding="utf-8")
        (ws / "docs" / "ddl.sql").write_text("create table t(id int);\n", encoding="utf-8")
        (ws / "docs" / "Notes.md").write_text("no title here\n", encoding="utf-8")
        subprocess.run(["git", "add", "docs"], cwd=ws, check=True)
        subprocess.run(["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "docs"], cwd=ws, check=True)
        plan = {s: d for s, d, _ in plan_migration(ws)}
        assert plan[".aizen/knowledge/system/architecture.md"] == "docs/architecture/architecture.md", plan
        assert plan[".aizen/knowledge/modules/seat-hold/seat-hold-api.md"] == "docs/api/seat-hold.md", plan
        assert plan["docs/SRS.md"] == "docs/product/srs.md" and plan["docs/ddl.sql"] == "docs/data/ddl.sql", plan
        assert ".aizen/knowledge/decisions.md" not in plan
        probs = check(ws)
        assert any("docs/SRS.md: at the docs/ root" in p for p in probs) and any("README.md missing" in p for p in probs), probs
        apply_migration(ws, plan_migration(ws))
        assert mode(ws) == "docs" and (ws / "docs/api/seat-hold.md").is_file() and (k / "decisions.md").is_file()
        assert where(ws, "module-api", "seat-hold") == "docs/api/seat-hold.md"
        assert modules(ws) == {"seat-hold": ["docs/api/seat-hold.md"]}, modules(ws)
        assert is_doc_path(ws, "docs/api/seat-hold.md") and not is_doc_path(ws, "src/a.py")
        st = subprocess.run(["git", "status", "--porcelain"], cwd=ws, capture_output=True, text=True).stdout
        assert "R  docs/SRS.md -> docs/product/srs.md" in st, st
        write_index(ws)
        idx = (ws / "docs" / "README.md").read_text(encoding="utf-8")
        assert "[Kiến trúc](architecture/architecture.md) | Tổng quan hệ thống." in idx, idx
        assert "### API — `api/`" in idx and "| [API giữ ghế](api/seat-hold.md)" in idx
        probs = check(ws)
        assert probs == ["docs/product/notes.md: no `# Title` on the first line"], probs
        (ws / "docs/product/notes.md").write_text("# Ghi chú\n\nXem [plan](../../.aizen/runs/T/plan.md).\n", encoding="utf-8")
        write_index(ws)
        assert any("links into .aizen/" in p for p in check(ws))
        # the owner's text above the marker survives a rebuild
        readme = ws / "docs" / "README.md"
        readme.write_text("# Docs\n\nViết tay.\n\n" + readme.read_text(encoding="utf-8").split(KEEP, 1)[1].join([KEEP, ""]),
                          encoding="utf-8")
        write_index(ws)
        assert readme.read_text(encoding="utf-8").startswith("# Docs\n\nViết tay.\n")
        assert kebab("User Stories_v2.MD") == "user-stories-v2.md" and kebab("ERDiagram.png") == "er-diagram.png"
        # a status line is not the summary; run ids and .aizen/ paths in the text are flagged
        (ws / ".aizen" / "archive" / "TET-0").mkdir(parents=True)
        (ws / ".aizen" / "runs" / "init").mkdir(parents=True)
        (ws / "docs/product/notes.md").write_text("# Ghi chú\n\n> DRAFT v3 · TET-0 · `.aizen/runs/TET-0/plan.md`\n\n## A\n",
                                                  encoding="utf-8")
        assert title_and_summary(ws / "docs/product/notes.md") == ("Ghi chú", "")
        probs = check(ws)
        assert any("mentions run id TET-0" in p for p in probs) and any("mentions .aizen/" in p for p in probs), probs
        assert any("no one-line summary" in p for p in probs) and not any("run id init" in p for p in probs), probs
        design = "# Thanh toán\n\nLuồng thanh toán.\n```mermaid\nsequenceDiagram\n```\n## Interface\nAPI POST /pay\n"
        assert guess("payment.md", design) == ("architecture/modules", False)
        assert guess("capacity.md") == ("architecture", True) and guess("misc.md") == ("product", False)
        (ws / "docs/architecture/hld.md").write_text("# HLD\n\nKiến trúc tổng thể.\n", encoding="utf-8")
        assert where(ws, "architecture") == "docs/architecture/architecture.md"  # the standard name exists → it wins
        (ws / "docs/architecture/architecture.md").unlink()
        assert where(ws, "architecture") == "docs/architecture/hld.md" and where(ws, "flows") == "docs/architecture/flows.md"
        (ws / "docs/data/data-model.md").write_text("# Data\n\nBảng chính.\n", encoding="utf-8")
        assert "data-model" not in modules(ws) and where(ws, "data") == "docs/data/data-model.md"
    print("docs.py self-check: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
